import { useState } from 'react'

const card = 'rounded-2xl border border-white/[0.08] bg-white/[0.035] backdrop-blur-sm'
const gradientText = 'bg-gradient-to-r from-[#4f89ff] to-[#a678ff] bg-clip-text text-transparent'

const steps = [['📁', 'Upload', 'PDF, notes, PPT, textbook'], ['🔍', 'Understand', 'AI analyzes your material'], ['📋', 'Plan', 'Personalized lesson structure'], ['🎓', 'Teach', 'Voice, visuals and interaction'], ['❓', 'Evaluate', 'Questions reveal understanding'], ['🔄', 'Adapt', 'Difficulty changes with you']]

export function HowItWorks() { return <section id="how-it-works" className="border-y border-white/[.05] bg-white/[.015] py-24"><div className="mx-auto max-w-7xl px-6"><div className="mb-14 text-center"><p className="mb-3 text-xs font-semibold uppercase tracking-[.25em] text-blue-400">How it works</p><h2 className="font-display text-4xl font-bold lg:text-5xl">From material to a <span className={gradientText}>real lesson.</span></h2></div><div className="grid grid-cols-2 gap-8 md:grid-cols-3 lg:grid-cols-6">{steps.map(([icon, title, text], index) => <div className="text-center" key={title}><div className={`mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl border text-2xl ${index === 5 ? 'border-violet-500/30 bg-violet-500/10' : 'border-blue-500/20 bg-blue-500/5'}`}>{icon}</div><h3 className="font-display font-semibold text-white">{title}</h3><p className="mt-1 text-[11px] leading-relaxed text-white/35">{text}</p></div>)}</div></div></section> }

export function AdaptiveTeaching() { return <section id="ai-teaching" className="py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 lg:grid-cols-2"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.25em] text-orange-400">Core intelligence</p><h2 className="font-display text-4xl font-bold leading-tight lg:text-5xl">When you struggle,<br /><span className={gradientText}>your teacher changes.</span></h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/45">The teaching loop observes understanding, detects misconceptions, and changes the explanation before asking you to try again.</p></div><div className={`${card} space-y-4 p-6`}><Message avatar="👩‍🏫" label="AI Teacher" text="What happens to current if resistance increases?" /><Message avatar="🧑‍💻" label="Student" text="Current increases." right /><div className="rounded-xl border border-orange-500/25 bg-orange-500/5 p-4"><p className="text-xs font-semibold text-orange-300">Misconception detected</p><p className="mt-2 text-sm text-white/60">The inverse relationship is not yet clear.</p></div><Message avatar="👩‍🏫" label="Adapting" text="Let's use a water-pipe analogy and try an easier question." /></div></div></section> }

function Message({ avatar, label, text, right = false }) { return <div className={`flex gap-3 ${right ? 'flex-row-reverse text-right' : ''}`}><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-violet-600 text-sm">{avatar}</span><div className={`${card} max-w-sm px-4 py-3`}><p className="mb-1 text-[10px] text-blue-400">{label}</p><p className="text-sm text-white/80">{text}</p></div></div> }

export function LearningProfile() { return <section id="learning-profile" className="bg-white/[.015] py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 lg:grid-cols-2"><div className={`${card} p-7`}><div className="flex items-center gap-6"><div className="relative flex h-28 w-28 items-center justify-center rounded-full border-[10px] border-blue-500/20 border-t-violet-500"><span className="font-display text-2xl font-bold">78%</span></div><div><p className="font-display text-lg font-semibold">Physics fundamentals</p><p className="mt-1 text-sm text-white/40">12 concepts completed</p><p className="mt-4 text-sm text-green-400">✓ Current · Voltage · Series circuits</p><p className="mt-2 text-sm text-amber-400">⚠ Resistance needs practice</p></div></div></div><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.25em] text-blue-400">Learning profile</p><h2 className="font-display text-4xl font-bold lg:text-5xl">Your progress becomes<br /><span className={gradientText}>your teacher's memory.</span></h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/45">Every answer helps the teacher understand your strengths, weak concepts, and the right next step.</p></div></div></section> }

export function Multilingual() { const [language, setLanguage] = useState('Hindi'); const messages = { English: 'Start with a clear explanation and a practical example.', Hindi: 'Bilkul! Chaliye is concept ko ek simple example se samajhte hain.', Hinglish: 'Sure! Is concept ko ek easy real-world example se break karte hain.' }; return <section className="py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 px-6 lg:grid-cols-2"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.25em] text-blue-400">Multilingual</p><h2 className="font-display text-4xl font-bold lg:text-5xl">Learn in the language<br /><span className={gradientText}>you understand best.</span></h2><div className="mt-7 flex flex-wrap gap-2">{Object.keys(messages).map((item) => <button key={item} onClick={() => setLanguage(item)} className={`rounded-lg border px-4 py-2 text-xs ${language === item ? 'border-transparent bg-gradient-to-r from-[#4f89ff] to-[#7c3aed] text-white' : 'border-white/10 text-white/50'}`}>{item}</button>)}</div></div><div className={`${card} p-6`}><p className="mb-4 text-xs text-white/35">Teaching in {language}</p><div className="rounded-2xl bg-white/[.06] p-4 text-sm leading-6 text-white/80">{messages[language]}</div></div></div></section> }
