import { useEffect, useState } from 'react'
import { BrowserRouter, Link, Route, Routes, useNavigate } from 'react-router-dom'
import AuthModal from './components/AuthModal'
import Button from './components/Button'
import HeroSection from './components/HeroSection'
import Navbar from './components/Navbar'
import { AdaptiveTeaching, HowItWorks, LearningProfile, Multilingual } from './components/LandingSections'
import { api } from './api'

function Home({ openAuth }) {
  return <><HeroSection onAuth={openAuth} /><HowItWorks /><AdaptiveTeaching /><LearningProfile /><Multilingual /><section className="relative overflow-hidden py-28 text-center"><div className="absolute inset-0 bg-gradient-to-b from-transparent via-blue-600/[.07] to-transparent" /><div className="relative mx-auto max-w-3xl px-6"><div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-r from-[#4f89ff] to-[#7c3aed] text-3xl">✦</div><h2 className="font-display text-5xl font-bold lg:text-6xl">Stop studying alone.</h2><p className="mx-auto mt-5 max-w-xl text-lg text-white/45">Bring your learning material. Choose your goal. Meet your AI Teacher.</p><Button onClick={() => openAuth('register')} className="mt-8 px-9 py-4 text-base">Start Learning →</Button></div></section><footer className="border-t border-white/[.06] py-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-6 text-xs text-white/30 sm:flex-row"><span>AI Teacher · Personalized learning powered by AI.</span><span>© 2026 AI Teacher</span></div></footer></>
}

function LearnPage() {
  const [profile, setProfile] = useState({ name: '', educational_level: 'bachelors', preferred_language: 'english', explanation_minutes: 20, preferred_style: 'beginner', progress: 0, topics_studied: [], weak_concepts: [], learning_history: [], current_learning_path: [] })
  const [saved, setSaved] = useState('')
  const navigate = useNavigate()
  useEffect(() => { api.getProfile().then(setProfile).catch(() => navigate('/')) }, [navigate])
  const update = (field, value) => setProfile((current) => ({ ...current, [field]: value }))
  const save = async (event) => { event.preventDefault(); setSaved('Saving...'); try { await api.updateProfile(profile); setSaved('Profile saved successfully') } catch (error) { setSaved(error.message) } }
  return <main className="min-h-screen bg-[#030b18] px-6 pb-16 pt-28 text-white"><div className="mx-auto max-w-4xl"><Link to="/" className="text-sm text-blue-400">← Back to AI Teacher</Link><div className="mt-8"><p className="text-xs uppercase tracking-[.25em] text-blue-400">Learner profile</p><h1 className="mt-3 font-display text-4xl font-bold lg:text-5xl">Build your learning path.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/45">These details help the teacher choose the right language, pace, depth and next concept.</p></div><form className="mt-10 grid gap-5 rounded-2xl border border-white/10 bg-white/[.035] p-6 md:grid-cols-2" onSubmit={save}><Field label="Your name" value={profile.name} onChange={(value) => update('name', value)} placeholder="Your name" /><Select label="Educational level" value={profile.educational_level} onChange={(value) => update('educational_level', value)} options={['bachelors', 'masters', 'school', 'other']} /><Select label="Language" value={profile.preferred_language} onChange={(value) => update('preferred_language', value)} options={['english', 'hindi', 'marathi', 'hinglish']} /><label><span className="mb-2 block text-xs text-white/50">Explain topic in how many minutes?</span><input className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white" type="number" min="1" max="240" value={profile.explanation_minutes} onChange={(event) => update('explanation_minutes', Number(event.target.value))} /></label><Select label="Preferred style" value={profile.preferred_style} onChange={(value) => update('preferred_style', value)} options={['beginner', 'intermediate', 'advanced']} /><label><span className="mb-2 block text-xs text-white/50">Progress (%)</span><input className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white" type="number" min="0" max="100" value={profile.progress} onChange={(event) => update('progress', Number(event.target.value))} /></label><TextList label="Topics studied" value={profile.topics_studied} onChange={(value) => update('topics_studied', value)} placeholder="Photosynthesis, algebra" /><TextList label="Weak concepts" value={profile.weak_concepts} onChange={(value) => update('weak_concepts', value)} placeholder="Add concepts separated by commas" /><TextList label="Learning history" value={profile.learning_history} onChange={(value) => update('learning_history', value)} placeholder="Topics and lessons completed" /><TextList label="Current learning path" value={profile.current_learning_path} onChange={(value) => update('current_learning_path', value)} placeholder="Concepts you want to learn next" /><div className="md:col-span-2 flex items-center gap-4"><button className="rounded-xl bg-gradient-to-r from-[#4f89ff] to-[#7c3aed] px-6 py-3 text-sm font-semibold">Save learner profile</button>{saved && <span className="text-sm text-blue-300">{saved}</span>}</div></form></div></main>
}

function Field({ label, value, onChange, placeholder }) { return <label><span className="mb-2 block text-xs text-white/50">{label}</span><input required className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none focus:border-blue-500" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label> }
function Select({ label, value, onChange, options }) { return <label><span className="mb-2 block text-xs text-white/50">{label}</span><select className="w-full rounded-xl border border-white/10 bg-[#0b1728] px-4 py-3 text-white" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label> }
function TextList({ label, value, onChange, placeholder }) { return <label className="md:col-span-2"><span className="mb-2 block text-xs text-white/50">{label}</span><textarea className="min-h-20 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none focus:border-blue-500" value={value.join(', ')} onChange={(event) => onChange(event.target.value.split(',').map((item) => item.trim()).filter(Boolean))} placeholder={placeholder} /></label> }

export default function App() {
  const [authModal, setAuthModal] = useState(null)
  return <BrowserRouter><div className="min-h-screen overflow-x-hidden bg-[#030b18] text-[#e8edf8]"><Navbar onAuth={setAuthModal} /><Routes><Route path="/" element={<Home openAuth={setAuthModal} />} /><Route path="/learn" element={<LearnPage />} /></Routes>{authModal && <AuthModal mode={authModal} onClose={() => setAuthModal(null)} onAuthenticated={() => { setAuthModal(null); window.location.href = '/learn' }} />}</div></BrowserRouter>
}
